default_agent: agent_main
agents:
  agent_main:
    name: agent_main
    entrypoint: agent_main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::792223357133:role/BedrockAgentCoreExecutionRole-development
      execution_role_auto_create: true
      account: '792223357133'
      region: us-east-1
      ecr_repository: 792223357133.dkr.ecr.us-east-1.amazonaws.com/aws-exam-agent-runtime-development
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agent_main-4h7OvMAtVL
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:792223357133:runtime/agent_main-4h7OvMAtVL
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-agent_main-builder
      execution_role: arn:aws:iam::792223357133:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-fd4e75a30a
      source_bucket: bedrock-agentcore-codebuild-sources-792223357133-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
