---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Exam Agent - DynamoDB テーブル設計（タスク4.1用）

Parameters:
  Environment:
    Type: String
    Default: development
    Description: 環境名
    AllowedValues:
      - development
      - staging
      - production

  ProjectName:
    Type: String
    Default: aws-exam-agent
    Description: プロジェクト名

Resources:
  # メインデータテーブル（単一テーブル設計）
  MainDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-data-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        # GSI1: サービス別・作成日時順クエリ用
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        # GSI2: 難易度別・品質スコア順クエリ用
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: MainDataStorage

  # キャッシュテーブル（TTL対応）
  CacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-cache-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: cache_key
          AttributeType: S
      KeySchema:
        - AttributeName: cache_key
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: CacheStorage

Outputs:
  MainDataTableName:
    Description: メインデータテーブル名
    Value: !Ref MainDataTable
    Export:
      Name: !Sub ${AWS::StackName}-MainDataTableName

  MainDataTableArn:
    Description: メインデータテーブル ARN
    Value: !GetAtt MainDataTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-MainDataTableArn

  MainDataTableStreamArn:
    Description: メインデータテーブル Stream ARN
    Value: !GetAtt MainDataTable.StreamArn
    Export:
      Name: !Sub ${AWS::StackName}-MainDataTableStreamArn

  CacheTableName:
    Description: キャッシュテーブル名
    Value: !Ref CacheTable
    Export:
      Name: !Sub ${AWS::StackName}-CacheTableName

  CacheTableArn:
    Description: キャッシュテーブル ARN
    Value: !GetAtt CacheTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CacheTableArn
